sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <formula>IF(ISBLANK(ImageUrlParameter__c),
    null,
    LEFT($Api.Partner_Server_URL_480, FIND(&quot;/services/Soap/&quot;, $Api.Partner_Server_URL_480))
        + &quot;/sfc/dist/version/renditionDownload?rendition=ORIGINAL_&quot; + FileType__c
        + &quot;&amp;versionId=&quot; + LEFT(ContentVersionId__c, 15)
        + &quot;&amp;d=/a/&quot; + ImageUrlParameter__c + &quot;&amp;oid=&quot; + LEFT($Organization.Id, 15)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>画像URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町名・番地</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel1__c.field-meta.xml
<CustomField>
    <fullName>Tel1__c</fullName>
    <inlineHelpText>直通番号や内線番号を入力します</inlineHelpText>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel2__c.field-meta.xml
<CustomField>
    <fullName>Tel2__c</fullName>
    <inlineHelpText>直通番号や内線番号を入力します</inlineHelpText>
    <label>電話番号2</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>代表電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>画像URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>携帯電話</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MyProfile__c.field-meta.xml
<CustomField>
    <fullName>MyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>マイプロフィール</label>
    <referenceTo>MyProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>OutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>親送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>ChildOutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>パスワード</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>都道府県</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>役職</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>表示回数</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCountLimit__c.field-meta.xml
<CustomField>
    <fullName>ViewCountLimit__c</fullName>
    <defaultValue>300</defaultValue>
    <label>表示回数制限</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ViewExpirationDate__c</fullName>
    <defaultValue>NOW()+14</defaultValue>
    <label>表示有効期限</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/OutboundProfilesSelector.cls
/**
 * Online Profile
 * 送信プロフィールSelector
 */
public with sharing class OutboundProfilesSelector extends AbstractSelector {
    private static final SObjectType SOBJECT_TYPE = OutboundProfile__c.sObjectType;

    private static final List<SObjectField> FIELD_LIST = new List<SObjectField> {
        OutboundProfile__c.Id, OutboundProfile__c.OwnerId, OutboundProfile__c.Parent__c,
        OutboundProfile__c.CompanyName__c, OutboundProfile__c.Website__c,
        OutboundProfile__c.PostalCode__c, OutboundProfile__c.State__c,
        OutboundProfile__c.City__c, OutboundProfile__c.Street__c,
        OutboundProfile__c.LastName__c, OutboundProfile__c.FirstName__c,
        OutboundProfile__c.Title__c, OutboundProfile__c.Department__c,
        OutboundProfile__c.Email__c, OutboundProfile__c.MobilePhone__c,
        OutboundProfile__c.Message__c, OutboundProfile__c.ImageUrl__c,
        OutboundProfile__c.ViewCount__c, OutboundProfile__c.ViewCountLimit__c,
        OutboundProfile__c.ViewExpirationDate__c, OutboundProfile__c.tel__c,
        OutboundProfile__c.tel1__c, OutboundProfile__c.tel2__c, OutboundProfile__c.Password__c
    };

    private static final String DEFAULT_ORDER_BY = 'CreatedDate ASC';

    public OutboundProfilesSelector() {
        super();
        setOrderBy(DEFAULT_ORDER_BY);
    }

    public override SObjectType getSObjectType() {
        return SOBJECT_TYPE;
    }

    public override List<SObjectField> getSObjectFieldList() {
        return FIELD_LIST;
    }

    public List<OutboundProfile__c> selectByParentId(Id parentId) {
        if (parentId == null) return new List<OutboundProfile__c>();

        String soql = String.format(
            'SELECT {0} FROM {1}'
                + ' WHERE Id = :parentId OR Parent__c = :parentId'
                + ' WITH SECURITY_ENFORCED'
                + ' ORDER BY {2} LIMIT {3}', new List<String> {

                getFieldsString(),
                getSObjectName(),
                'CompanyName__c,Parent__c NULLS FIRST, Title__c NULLS LAST, Department__c NULLS LAST,'
                    + ' LastName__c, FirstName__c, Email__c',
                getLimit()
            }
        );
        return (List<OutboundProfile__c>)Database.query(soql);
    }

    public List<OutboundProfile__c> selectByMyProfileId(Id myProfId) {
        if (myProfId == null) return new List<OutboundProfile__c>();

        String soql = String.format(
            'SELECT {0} FROM {1}'
                + ' WHERE MyProfile__c = :myProfId'
                + ' WITH SECURITY_ENFORCED'
                + ' ORDER BY {2} LIMIT {3}', new List<String> {

                getFieldsString(),
                getSObjectName(),
                'Parent__c NULLS FIRST, Title__c NULLS LAST, Department__c NULLS LAST,'
                    + ' LastName__c, FirstName__c, Email__c',
                getLimit()
            }
        );
        return (List<OutboundProfile__c>)Database.query(soql);
    }
}