sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <label>コンテンツバージョンID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/FileType__c.field-meta.xml
<CustomField>
    <fullName>FileType__c</fullName>
    <label>ファイルの種類</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <formula>IF(ISBLANK(ImageUrlParameter__c),
    null,
    LEFT($Api.Partner_Server_URL_480, FIND(&quot;/services/Soap/&quot;, $Api.Partner_Server_URL_480))
        + &quot;/sfc/dist/version/renditionDownload?rendition=ORIGINAL_&quot; + FileType__c
        + &quot;&amp;versionId=&quot; + LEFT(ContentVersionId__c, 15)
        + &quot;&amp;d=/a/&quot; + ImageUrlParameter__c + &quot;&amp;oid=&quot; + LEFT($Organization.Id, 15)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>画像URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrlParameter__c.field-meta.xml
<CustomField>
    <fullName>ImageUrlParameter__c</fullName>
    <label>画像URLパラメータ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>画像URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MyProfile__c.field-meta.xml
<CustomField>
    <fullName>MyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>マイプロフィール</label>
    <referenceTo>MyProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>OutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ImageRegisterService.cls
/**
 * Online Profile
 * 画像登録Service
 */
public with sharing class ImageRegisterService {
    /**
     * 画像登録/更新
     */
    public static Image upsertImage(Image registImage) {
        Savepoint sp = Database.setSavepoint();
        try {
            MyProfile__c prof = registImage.prof;
            ContentVersion conVer = registImage.conVer;

            // コンテンツバージョン作成
            ContentVersionsSelector conVerSelector = new ContentVersionsSelector();
            ContentVersion oldConVer = conVerSelector.selectById(prof.ContentVersionId__c);
            ContentVersion newConVer = new ContentVersion(
                VersionData = conVer.VersionData,
                PathOnClient = conVer.PathOnClient
            );

            if (oldConVer != null) {
                newConVer.ContentDocumentId = oldConVer.ContentDocumentId;
                newConVer.Title = newConVer.PathOnClient.substringBeforeLast('.');
            } else {
                newConVer.FirstPublishLocationId = prof.Id;
            }
            createSObject(new List<SObject> { newConVer });
            newConVer = conVerSelector.selectById(newConVer.Id);

            // コンテンツ配信作成
            ContentDistribution newConDist = new ContentDistribution(
                ContentVersionId = newConVer.Id,
                Name = newConVer.Title,
                PreferencesPasswordRequired = false
            );
            createSObject(new List<SObject> { newConDist });
            newConDist = new ContentDistributionsSelector().selectById(newConDist.Id);

            // マイプロフィール更新
            MyProfile__c updProf = new MyProfile__c(
                Id = prof.Id,
                ContentVersionId__c = newConVer.Id,
                FileType__c = newConVer.FileType,
                ImageUrlParameter__c = newConDist.DistributionPublicUrl.substringAfter('/a/')
            );
            updateSObject(new List<SObject> { updProf });
            registImage.prof = new MyProfilesSelector().selectById(prof.Id);
            return registImage;
        } catch (Exception ex) {
            Database.rollback(sp);
            throw ex;
        }
    }

    /**
     * 画像削除
     */
    public static Image deleteImage(Image registImage) {
        MyProfile__c prof = registImage.prof;
        Savepoint sp = Database.setSavepoint();
        try {
            //コンテンツドキュメント削除
            ContentVersionsSelector conVerSelector = new ContentVersionsSelector();
            ContentVersion currentConVer = conVerSelector.selectById(prof.ContentVersionId__c);
            ContentDocument currentConDoc = new ContentDocument(Id=currentConVer.ContentDocumentId);
            deleteSObject(new List<SObject> { currentConDoc });
            
            //マイプロフィール更新
            MyProfile__c updProf = new MyProfile__c(
                    Id = prof.Id,
                    ContentVersionId__c = null,
                    FileType__c = null,
                    ImageUrlParameter__c = null
                );
            updateSObject(new List<SObject> { updProf });

            //送信プロフィール更新(あれば)
            List<OutboundProfile__c> outProfList = new OutboundProfilesSelector().selectByMyProfileId(prof.Id);
            for ( OutboundProfile__c outProf:outProfList ){
                outProf.ImageUrl__c = null;
            }
            updateSObject(outProfList);
            registImage.prof = new MyProfilesSelector().selectById(prof.Id);
            return registImage;
        } catch (Exception ex) {
            Database.rollback(sp);
            throw ex;
        }
    }

    /* 複数処理する形にしないとCode Scannerを通せない */
    private static List<Database.SaveResult> createSObject(List<SObject> sobjList) {
        return Database.insert(CrudFlsChecker.checkCreate(sobjList), true);
    }

    private static List<Database.SaveResult> updateSObject(List<SObject> sobjList) {
        return Database.update(CrudFlsChecker.checkUpdate(sobjList), true);
    }

    private static List<Database.DeleteResult> deleteSObject(List<SObject> sobjList) {
        return Database.delete(CrudFlsChecker.checkDelete(sobjList), true);
    }

    public with sharing class Image {
        public MyProfile__c prof { get; set; }
        public final ContentVersion conVer { get; private set; }

        public Image(MyProfile__c prof, ContentVersion conVer) {
            this.prof = prof;
            this.conVer = conVer;
        }
    }

    public class ImageRegisterServiceException extends Exception {}
}