sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MyProfile__c.field-meta.xml
<CustomField>
    <fullName>MyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>マイプロフィール</label>
    <referenceTo>MyProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>OutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>親送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>ChildOutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/OutboundProfilesSelectorTest.cls
/**
 * Online Profile
 * 送信プロフィールSelector
 * Test
 */
@IsTest
private with sharing class OutboundProfilesSelectorTest {
    @TestSetup
    private static void setup() {
        List<OutboundProfile__c> profList = TestDataFactory.createOutboundProfileList(200);
    }

    @IsTest
    private static void selectById() {
        List<OutboundProfile__c> profList = TestDataFactory.getOutboundProfileList(200);
        Id parentId = profList.get(0).Id;
        for (Integer i = 1; i < profList.size(); i++) {
            profList.get(i).Parent__c = parentId;
        }
        update profList;

        Test.startTest();

        OutboundProfilesSelector selector = new OutboundProfilesSelector();
        List<OutboundProfile__c> resultProf = selector.selectByParentId(parentId);

        Test.stopTest();

        System.assertEquals(Integer.valueOf(selector.getLimit()), resultProf.size());
    }

    @IsTest
    private static void selectByMyProfileId() {
        List<MyProfile__c> myProfList = TestDataFactory.newMyProfileList(1);
        insert myProfList;

        List<OutboundProfile__c> profList = TestDataFactory.getOutboundProfileList(200);
        Id parentId = profList.get(0).Id;
        for (Integer i = 1; i < profList.size(); i++) {
            profList.get(i).MyProfile__c = myProfList[0].Id;
        }
        update profList;

        Test.startTest();

        OutboundProfilesSelector selector = new OutboundProfilesSelector();
        List<OutboundProfile__c> resultProf = selector.selectByMyProfileId(myProfList[0].Id);

        Test.stopTest();

        System.assertEquals(Integer.valueOf(selector.getLimit()), resultProf.size());
    }
}