sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>メインプロフィール</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/MyProfileTriggerHandlerTest.cls
/**
 * Online Profile
 * マイプロフィールトリガハンドラ
 * Test
 */
@IsTest
private with sharing class MyProfileTriggerHandlerTest {
    @IsTest
    private static void test() {
        Test.startTest();

        List<MyProfile__c> profList = TestDataFactory.createMyProfileList(200);
        for (MyProfile__c prof : profList) {
            prof.IsDefault__c = true;
        }
        update profList;

        Test.stopTest();

        System.assertEquals(200, TestDataFactory.getMyProfileList(200).size());
    }
}