sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <label>コンテンツバージョンID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <formula>IF(ISBLANK(ImageUrlParameter__c),
    null,
    LEFT($Api.Partner_Server_URL_480, FIND(&quot;/services/Soap/&quot;, $Api.Partner_Server_URL_480))
        + &quot;/sfc/dist/version/renditionDownload?rendition=ORIGINAL_&quot; + FileType__c
        + &quot;&amp;versionId=&quot; + LEFT(ContentVersionId__c, 15)
        + &quot;&amp;d=/a/&quot; + ImageUrlParameter__c + &quot;&amp;oid=&quot; + LEFT($Organization.Id, 15)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>画像URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ImageRegisterController.cls
/**
 * Online Profile
 * 画像登録コントローラ
 */
public with sharing class ImageRegisterController {
    public MyProfile__c myProfile { get; private set; }
    public String imageUrl { get; private set; }
    public final ContentVersion contentVersion { get; set; }

    public ImageRegisterController(ApexPages.StandardController stdController) {
        try {
            if (!Test.isRunningTest()) {
                stdController.addFields(new List<String> { 'ContentVersionId__c', 'ImageUrl__c' });
            }
            myProfile = (MyProfile__c)stdController.getRecord();
            imageUrl = UrlProofreader.fix(myProfile.ImageUrl__c);
            contentVersion = new ContentVersion();
        } catch (Exception ex) {
            PagesMessage.error(ex);
        }
    }

    public void save() {
        try {
            if (contentVersion.VersionData == null) {
                throw new ImageRegisterControllerException('画像を選択してください');
            }

            ImageRegisterService.Image registImage = new ImageRegisterService.Image(myProfile, contentVersion);
            registImage = ImageRegisterService.upsertImage(registImage);
            myProfile = registImage.prof;
            imageUrl = UrlProofreader.fix(myProfile.ImageUrl__c);
            // ビューステートサイズオーバー対策、アップロード成功時にはVersionDataをNullにしておく
            contentVersion.VersionData = null;

        } catch (ImageRegisterControllerException ex) {
            PagesMessage.warn(ex);
        } catch (Exception ex) {
            PagesMessage.error(ex);
        }
    }

    public void deleteImage() {
        try {
            if (imageUrl == null) {
                throw new ImageRegisterControllerException('画像がアップロードされていません。');
            }
            ImageRegisterService.Image registImage = new ImageRegisterService.Image(myProfile, contentVersion);
            registImage = ImageRegisterService.deleteImage(registImage);
            myProfile = registImage.prof;
            imageUrl = null;

        } catch (ImageRegisterControllerException ex) {
            PagesMessage.warn(ex);
        } catch (Exception ex) {
            PagesMessage.error(ex);
        }
    }

    public class ImageRegisterControllerException extends Exception {}
}