sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <formula>IF(ISBLANK(ImageUrlParameter__c),
    null,
    LEFT($Api.Partner_Server_URL_480, FIND(&quot;/services/Soap/&quot;, $Api.Partner_Server_URL_480))
        + &quot;/sfc/dist/version/renditionDownload?rendition=ORIGINAL_&quot; + FileType__c
        + &quot;&amp;versionId=&quot; + LEFT(ContentVersionId__c, 15)
        + &quot;&amp;d=/a/&quot; + ImageUrlParameter__c + &quot;&amp;oid=&quot; + LEFT($Organization.Id, 15)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>画像URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町名・番地</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel1__c.field-meta.xml
<CustomField>
    <fullName>Tel1__c</fullName>
    <inlineHelpText>直通番号や内線番号を入力します</inlineHelpText>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel2__c.field-meta.xml
<CustomField>
    <fullName>Tel2__c</fullName>
    <inlineHelpText>直通番号や内線番号を入力します</inlineHelpText>
    <label>電話番号2</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>代表電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OnlineProfileConfig__c/OnlineProfileConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Online Profile</label>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OnlineProfileConfig__c/fields/BaseUrl__c.field-meta.xml
<CustomField>
    <fullName>BaseUrl__c</fullName>
    <label>ベースURL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>送信プロフィール作成日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ExchangeProfileUrl__c.field-meta.xml
<CustomField>
    <fullName>ExchangeProfileUrl__c</fullName>
    <label>プロフィール交換URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>画像URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/InboundProfileNotificationFlg__c.field-meta.xml
<CustomField>
    <fullName>InboundProfileNotificationFlg__c</fullName>
    <defaultValue>true</defaultValue>
    <label>受信プロフィール通知要否</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>携帯電話</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MyProfile__c.field-meta.xml
<CustomField>
    <fullName>MyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>マイプロフィール</label>
    <referenceTo>MyProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>OutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>親送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>ChildOutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>パスワード</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>都道府県</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>役職</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>表示回数</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCountLimit__c.field-meta.xml
<CustomField>
    <fullName>ViewCountLimit__c</fullName>
    <defaultValue>300</defaultValue>
    <label>表示回数制限</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ViewExpirationDate__c</fullName>
    <defaultValue>NOW()+14</defaultValue>
    <label>表示有効期限</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/OutboundProfiles.cls
/**
 * Online Profile
 * 送信プロフィール
 */
public with sharing class OutboundProfiles {
    private final OnlineProfileConfig__c config = OnlineProfileConfig__c.getOrgDefaults();
    private final OutboundProfile__c outProf;
    private List<OutboundProfile__c> memberOutProfs = new List<OutboundProfile__c>();
    private String exchangeProfileUrl;

    public OutboundProfiles(MyProfile__c myProf, Decimal viewCountLimit, Datetime viewExpirationDate, String password, Boolean isSendNotify) {
        if (config == null) {
            throw new OutboundProfilesException('カスタム設定を設定してください。');
        }
        if (myProf == null) {
            throw new OutboundProfilesException('マイプロフィールを指定してください。');
        }
        outProf = getOutboundProfile(myProf, null, viewCountLimit, viewExpirationDate, password, isSendNotify);
    }

    public void setMemberProfiles(List<MyProfile__c> memberMyProfs, Decimal viewCountLimit, Datetime viewExpirationDate, String password, Boolean isSendNotify) {
        memberOutProfs.clear();
        if (memberMyProfs == null) return;
        if (outProf == null) {
            throw new OutboundProfilesException('送信プロフィールを作成してください。');
        }

        for (MyProfile__c memberMyProf : memberMyProfs) {
            memberOutProfs.add(getOutboundProfile(memberMyProf, outProf.Id,viewCountLimit,viewExpirationDate,password,isSendNotify));
        }
    }

    private OutboundProfile__c getOutboundProfile(MyProfile__c myProf, Id parentId, Decimal viewCountLimit, Datetime viewExpirationDate, String password, Boolean isSendNotify) {
        OutboundProfile__c outProf = new OutboundProfile__c();
        outProf.MyProfile__c = myProf.Id;
        outProf.Parent__c = parentId;
        outProf.CompanyName__c = myProf.CompanyName__c;
        outProf.PostalCode__c = myProf.PostalCode__c;
        outProf.State__c = myProf.State__c;
        outProf.City__c = myProf.City__c;
        outProf.Street__c = myProf.Street__c;
        outProf.LastName__c = myProf.LastName__c;
        outProf.FirstName__c = myProf.FirstName__c;
        outProf.Department__c = myProf.Department__c;
        outProf.Title__c = myProf.Title__c;
        outProf.Email__c = myProf.Email__c;
        outProf.tel__c = myProf.tel__c;
        outProf.tel1__c = myProf.tel1__c;
        outProf.tel2__c = myProf.tel2__c;
        outProf.MobilePhone__c = myProf.MobilePhone__c;
        outProf.Message__c = myProf.Message__c;
        outProf.ImageUrl__c = UrlProofreader.fix(myProf.ImageUrl__c);
        outProf.CreatedDate__c = Datetime.now();
        outProf.ViewCount__c = 0;
        outProf.InboundProfileNotificationFlg__c = isSendNotify;
        if (String.isNotBlank(password)){
            outProf.Password__c = CryptUtil.createHashedPassword(password);
        }
        // Webサイト転記漏れ
        outProf.Website__c = myProf.Website__c;
        if (viewCountLimit != null) {
            outProf.ViewCountLimit__c = viewCountLimit;
        }
        if (viewExpirationDate != null) {
            outProf.ViewExpirationDate__c = viewExpirationDate;
        }
        return outProf;
    }

    public OutboundProfile__c getProfile() {
        return outProf;
    }

    public List<OutboundProfile__c> getMemberProfiles() {
        return memberOutProfs;
    }

    public void generateExchangeProfileUrl() {
        if (outProf == null) {
            throw new OutboundProfilesException('送信プロフィールを作成してください。');
        }
        if (String.isBlank(config.BaseUrl__c)) {
            throw new OutboundProfilesException('ベースURLを設定してください。');
        }
        String url = config.BaseUrl__c.removeEnd('/') + '/?' + CryptUtil.createEncryptedRecordId(outProf.Id);
        outProf.ExchangeProfileUrl__c = url;
        for (OutboundProfile__c memberOutProf : memberOutProfs) {
            memberOutProf.ExchangeProfileUrl__c = url;
        }
        exchangeProfileUrl = url;
    }

    public String getExchangeProfileUrl() {
        if (String.isBlank(exchangeProfileUrl)) {
            throw new OutboundProfilesException('プロフィール交換URLを生成してください。');
        }
        return exchangeProfileUrl;
    }

    public class OutboundProfilesException extends Exception {}
}