sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>メインプロフィール</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/MyProfilesServiceTest.cls
/**
 * Online Profile
 * マイプロフィールService
 * Test
 */
@IsTest
private with sharing class MyProfilesServiceTest {
    @TestSetup
    private static void setup() {
        TestDataFactory.createMyProfileList(200);
    }

/*
    @IsTest
    private static void setDefault() {
        List<MyProfile__c> profList = TestDataFactory.getMyProfileList(200);
        for (MyProfile__c prof : profList) {
            prof.IsDefault__c = true;
        }

        Test.startTest();
        MyProfilesService.setDefault(profList);
        Test.stopTest();

        Integer count = 0;
        for (MyProfile__c prof : TestDataFactory.getMyProfileList(200)) {
            if (!prof.IsDefault__c) continue;
            count++;
        }
        System.assertEquals(1, count);
    }
*/
}