sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <formula>IF(ISBLANK(ImageUrlParameter__c),
    null,
    LEFT($Api.Partner_Server_URL_480, FIND(&quot;/services/Soap/&quot;, $Api.Partner_Server_URL_480))
        + &quot;/sfc/dist/version/renditionDownload?rendition=ORIGINAL_&quot; + FileType__c
        + &quot;&amp;versionId=&quot; + LEFT(ContentVersionId__c, 15)
        + &quot;&amp;d=/a/&quot; + ImageUrlParameter__c + &quot;&amp;oid=&quot; + LEFT($Organization.Id, 15)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>画像URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ImageRegisterControllerTest.cls
/**
 * Online Profile
 * 画像登録コントローラ
 * Test
 */
@IsTest
private with sharing class ImageRegisterControllerTest {
    @TestSetup
    private static void setup() {
        TestDataFactory.createMyProfile();
    }

    @IsTest
    private static void save() {
        MyProfile__c prof = TestDataFactory.getMyProfile();

        PageReference pageRef = Page.ImageRegister;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController standardController = new ApexPages.StandardController(prof);

        Test.startTest();

        ImageRegisterController controller = new ImageRegisterController(standardController);
        controller.contentVersion.VersionData = Blob.valueOf('test');
        controller.contentVersion.PathOnClient = 'test.png';
        controller.save();

        Test.stopTest();

        prof = TestDataFactory.getMyProfile();
        System.assertNotEquals(null, prof.ImageUrl__c);
    }

    @IsTest
    private static void deleteImage() {
        MyProfile__c prof = TestDataFactory.getMyProfile();

        PageReference pageRef = Page.ImageRegister;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController standardController = new ApexPages.StandardController(prof);

        

        ImageRegisterController controller = new ImageRegisterController(standardController);
        controller.contentVersion.VersionData = Blob.valueOf('test');
        controller.contentVersion.PathOnClient = 'test.png';
        controller.save();

        Test.startTest();
        controller.deleteImage();
        Test.stopTest();

        prof = TestDataFactory.getMyProfile();
        System.assertEquals(null, prof.ImageUrl__c);
    }

    @IsTest
    private static void versionDataWithNull() {
        MyProfile__c prof = TestDataFactory.getMyProfile();

        PageReference pageRef = Page.ImageRegister;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController standardController = new ApexPages.StandardController(prof);

        Test.startTest();

        ImageRegisterController controller = new ImageRegisterController(standardController);
        controller.contentVersion.VersionData = null;
        controller.contentVersion.PathOnClient = null;
        controller.save();

        Test.stopTest();

        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }

    @IsTest
    private static void throwException() {
        MyProfile__c prof = TestDataFactory.getMyProfile();

        PageReference pageRef = Page.ImageRegister;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController standardController = new ApexPages.StandardController(prof);

        Test.startTest();

        ImageRegisterController controller = new ImageRegisterController(standardController);
        controller.contentVersion.VersionData = Blob.valueOf('test');
        controller.contentVersion.PathOnClient = 'test.png';
        controller.myProfile.Id = null;
        controller.save();

        Test.stopTest();

        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }
}