sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ProfileExchangerTest.cls
/**
 * Online Profile
 * プロフィール交換
 * Test
 */
@IsTest
private with sharing class ProfileExchangerTest {
    @TestSetup
    private static void setup() {
        TestDataFactory.createOutboundProfileList(200);
    }

    @IsTest
    private static void test() {
        List<OutboundProfile__c> outProfList = TestDataFactory.getOutboundProfileList(200);

        Test.startTest();

        ProfileExchanger profExchanger = new ProfileExchanger(outProfList);
        System.assertEquals(true, profExchanger.hasOutboundProfile());
        System.assertEquals(false, profExchanger.isExpired());
        System.assert(String.isNotBlank(profExchanger.getCompanyName()));
        System.assert(String.isNotBlank(profExchanger.getOutboundProfile().Email__c));
        System.assert(!profExchanger.getOutboundProfileList().isEmpty());
        System.assert(!profExchanger.getOutProfileMaps().isEmpty());
        System.assert(String.isNotBlank(profExchanger.getTextProfiles()));
        System.assert(profExchanger.getInboundProfile() != null);

        Test.stopTest();
    }
}