sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>送信プロフィール作成日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/CryptUtilTest.cls
/**
 * Online Profile
 * CryptUtil
 * Test
 */
@IsTest
private with sharing class CryptUtilTest {

    @IsTest
    private static void createHashedPassword () {
        String password = 'test0001';

        Test.startTest();
        String hashedPassword = CryptUtil.createHashedPassword(password) ;
        Test.stopTest();

        System.assertNotEquals(null, hashedPassword);
    }
    @IsTest
    private static void createEncryptedRecordId () {
		OutboundProfile__c op = new OutboundProfile__c(
        	LastName__c = 'SEI',
        	FirstName__c  = 'MEI',
            Email__c   = 'test@example.com',
            CreatedDate__c = System.today()
        );
        insert op;
        Test.startTest();
        String encrypedId = CryptUtil.createEncryptedRecordId(op.Id) ;
        String recordId = CryptUtil.decryptEncryptedRecordId(encrypedId) ;
        Test.stopTest();

        System.assertNotEquals(null, encrypedId);
        System.assertEquals(op.Id, recordId);
    }
}