sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/CsvDownloaderTest.cls
/**
 * Online Profile
 * CSVダウンローダ
 * Test
 */
@IsTest
private with sharing class CsvDownloaderTest {
    @TestSetup
    private static void setup() {
        TestDataFactory.createOutboundProfileList(200);
    }

    @IsTest
    private static void testAC() {
        List<OutboundProfile__c> profList = TestDataFactory.getOutboundProfileList(200);
        String filename = 'text.csv';

        Test.startTest();
        FileDownloader downloader = new CsvDownloader(profList, filename, 'Windows-31J','AC');
        Test.stopTest();

        System.assert(downloader.getContentDisposition().contains(filename));
        System.assert(downloader.getContentType().contains(filename));
        System.assert(downloader.getBody().contains(profList.get(0).Email__c));
    }

    @IsTest
    private static void testOP() {
        List<OutboundProfile__c> profList = TestDataFactory.getOutboundProfileList(200);
        String filename = 'text.csv';

        Test.startTest();
        FileDownloader downloader = new CsvDownloader(profList, filename, 'Windows-31J','OP');
        Test.stopTest();

        System.assert(downloader.getContentDisposition().contains(filename));
        System.assert(downloader.getContentType().contains(filename));
        System.assert(downloader.getBody().contains(profList.get(0).Email__c));
    }

    @IsTest
    private static void testSV() {
        List<OutboundProfile__c> profList = TestDataFactory.getOutboundProfileList(200);
        String filename = 'text.csv';

        Test.startTest();
        FileDownloader downloader = new CsvDownloader(profList, filename, 'Windows-31J','SV');
        Test.stopTest();

        System.assert(downloader.getContentDisposition().contains(filename));
        System.assert(downloader.getContentType().contains(filename));
        System.assert(downloader.getBody().contains(profList.get(0).Email__c));
    }
}