sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/InboundProfile__c.object-meta.xml
<CustomObject>
    <label>受信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>受信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>名</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/OutboundProfile__c.field-meta.xml
<CustomField>
    <fullName>OutboundProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>受信プロフィール</relationshipLabel>
    <relationshipName>InboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ViewExpirationDate__c</fullName>
    <defaultValue>NOW()+14</defaultValue>
    <label>表示有効期限</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ProfileExchangerControllerTest.cls
/**
 * Online Profile
 * プロフィール交換コントローラ
 * Test
 */
@IsTest
private with sharing class ProfileExchangerControllerTest {
    @TestSetup
    private static void setup() {
        TestDataFactory.createOutboundProfile();
    }

    @IsTest
    private static void saveInboundProfile() {
        OutboundProfile__c prof = TestDataFactory.getOutboundProfile();

        PageReference pageRef = Page.ProfileExchanger;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put(CryptUtil.createEncryptedRecordId(prof.Id), null);

        Test.startTest();

        ProfileExchangerController controller = new ProfileExchangerController();
        controller.init();
        controller.viewPage();
        controller.inputPage();
        controller.messagePage();
        controller.outProfileId = prof.Id;
        controller.downloadVCard();
        controller.downloadCsv();
        controller.inProfile.LastName__c = '名刺';
        controller.inProfile.FirstName__c = '太郎';
        String email = 'meishi@example.com';
        controller.inProfile.Email__c = email;
        controller.saveInboundProfile();

        Test.stopTest();

        InboundProfile__c inProf = TestDataFactory.getInboundProfile();
        System.assertEquals(email, inProf.Email__c);
    }

    @IsTest
    private static void idWithNull() {
        PageReference pageRef = Page.ProfileExchanger;
        Test.setCurrentPage(pageRef);

        Test.startTest();

        ProfileExchangerController controller = new ProfileExchangerController();
        controller.init();

        Test.stopTest();

        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }

    @IsTest
    private static void idWithNotExist() {
        PageReference pageRef = Page.ProfileExchanger;
        ApexPages.currentPage().getParameters().put('xx_xxxxx', null);
        Test.setCurrentPage(pageRef);

        Test.startTest();

        ProfileExchangerController controller = new ProfileExchangerController();
        controller.init();

        Test.stopTest();

        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }

    @IsTest
    private static void idWithExpired() {
        OutboundProfile__c prof = TestDataFactory.getOutboundProfile();
        prof.ViewExpirationDate__c = Datetime.now().addDays(-1);
        update prof;

        PageReference pageRef = Page.ProfileExchanger;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put(CryptUtil.createEncryptedRecordId(prof.Id), null);

        Test.startTest();

        ProfileExchangerController controller = new ProfileExchangerController();
        controller.init();

        Test.stopTest();

        System.assert(ApexPages.hasMessages(ApexPages.severity.ERROR));
    }
}