sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/InboundProfile__c.object-meta.xml
<CustomObject>
    <label>受信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>受信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>受信プロフィール作成日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/OutboundProfile__c.field-meta.xml
<CustomField>
    <fullName>OutboundProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>受信プロフィール</relationshipLabel>
    <relationshipName>InboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>送信プロフィール作成日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>表示回数</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ProfileExchangerService.cls
/**
 * Online Profile
 * プロフィール交換Service
 */
public with sharing class ProfileExchangerService {
    /** 表示回数更新 */
    public static List<Database.SaveResult> updateViewCount(List<OutboundProfile__c> outProfList) {
        List<OutboundProfile__c> updOutProfList = new List<OutboundProfile__c>();
        for (OutboundProfile__c outProf : outProfList) {
            Decimal viewCount = (outProf.ViewCount__c != null) ? outProf.ViewCount__c : 0;
            viewCount++;
            updOutProfList.add(new OutboundProfile__c(Id=outProf.Id, ViewCount__c=viewCount));
        }
        return new SystemMode().updateSObject(updOutProfList);
    }

    /** 受信プロフィール作成 */
    public static List<Database.SaveResult> createInboundProfile(List<InboundProfile__c> profList) {
        for (InboundProfile__c prof : profList) {
            prof.CreatedDate__c = Datetime.now();
        }
        return new SystemMode().createSObject(profList);
    }

    /**
     * システムモードでDML実行
     * ゲストユーザに付与できる共有アクセス権は参照のみ
     */
    private without sharing class SystemMode {
        public List<Database.SaveResult> createSObject(List<SObject> sobjList) {
            return Database.insert(CrudFlsChecker.checkCreate(sobjList), true);
        }

        public List<Database.SaveResult> updateSObject(List<SObject> sobjList) {
            return Database.update(CrudFlsChecker.checkUpdate(sobjList), true);
        }
    }
}