sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/InboundProfile__c.object-meta.xml
<CustomObject>
    <label>受信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>受信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区郡</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>受信プロフィール作成日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>部署</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>名</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>メッセージ</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/OutboundProfile__c.field-meta.xml
<CustomField>
    <fullName>OutboundProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>受信プロフィール</relationshipLabel>
    <relationshipName>InboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>郵便番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町名・番地</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/Tel1__c.field-meta.xml
<CustomField>
    <fullName>Tel1__c</fullName>
    <inlineHelpText>直通番号や内線番号を記入します</inlineHelpText>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/Tel2__c.field-meta.xml
<CustomField>
    <fullName>Tel2__c</fullName>
    <inlineHelpText>直通番号や内線番号を記入します</inlineHelpText>
    <label>電話番号2</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <label>Web サイト</label>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/MyProfile__c.object-meta.xml
<CustomObject>
    <label>マイプロフィール</label>
    <nameField>
        <label>プロフィール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ContentVersionId__c.field-meta.xml
<CustomField>
    <fullName>ContentVersionId__c</fullName>
    <label>コンテンツバージョンID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <formula>IF(ISBLANK(ImageUrlParameter__c),
    null,
    LEFT($Api.Partner_Server_URL_480, FIND(&quot;/services/Soap/&quot;, $Api.Partner_Server_URL_480))
        + &quot;/sfc/dist/version/renditionDownload?rendition=ORIGINAL_&quot; + FileType__c
        + &quot;&amp;versionId=&quot; + LEFT(ContentVersionId__c, 15)
        + &quot;&amp;d=/a/&quot; + ImageUrlParameter__c + &quot;&amp;oid=&quot; + LEFT($Organization.Id, 15)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>画像URL</label>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>メインプロフィール</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>町名・番地</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel1__c.field-meta.xml
<CustomField>
    <fullName>Tel1__c</fullName>
    <inlineHelpText>直通番号や内線番号を入力します</inlineHelpText>
    <label>電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel2__c.field-meta.xml
<CustomField>
    <fullName>Tel2__c</fullName>
    <inlineHelpText>直通番号や内線番号を入力します</inlineHelpText>
    <label>電話番号2</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/MyProfile__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>代表電話番号</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OnlineProfileConfig__c/OnlineProfileConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Online Profile</label>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OnlineProfileConfig__c/fields/BaseUrl__c.field-meta.xml
<CustomField>
    <fullName>BaseUrl__c</fullName>
    <label>ベースURL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OnlineProfileConfig__c/fields/DefaultViewCountLimit__c.field-meta.xml
<CustomField>
    <fullName>DefaultViewCountLimit__c</fullName>
    <defaultValue>300</defaultValue>
    <label>デフォルト表示回数制限</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OnlineProfileConfig__c/fields/DefaultViewExpirationDays__c.field-meta.xml
<CustomField>
    <fullName>DefaultViewExpirationDays__c</fullName>
    <defaultValue>14</defaultValue>
    <label>デフォルト表示有効日数</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <label>送信プロフィール作成日</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>画像URL</label>
    <type>Url</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>携帯電話</label>
    <type>Phone</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/MyProfile__c.field-meta.xml
<CustomField>
    <fullName>MyProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>マイプロフィール</label>
    <referenceTo>MyProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>OutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>親送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>送信プロフィール</relationshipLabel>
    <relationshipName>ChildOutboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>都道府県</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>役職</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>表示回数</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCountLimit__c.field-meta.xml
<CustomField>
    <fullName>ViewCountLimit__c</fullName>
    <defaultValue>300</defaultValue>
    <label>表示回数制限</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ViewExpirationDate__c</fullName>
    <defaultValue>NOW()+14</defaultValue>
    <label>表示有効期限</label>
    <type>DateTime</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/TestDataFactory.cls
/**
 * テストデータ作成
 */
@IsTest
public with sharing class TestDataFactory {
    private TestDataFactory() {}

    public static User getGuestUser() {
        return [SELECT Id FROM User WHERE UserType = 'Guest' LIMIT 1];
    }

    public static Account newAccount(String name, String website) {
        return new Account(
            Name = name,
            Website = website
        );
    }

    public static Account newAccount() {
        return newAccount('株式会社サンブリッジ', 'https://www.sunbridge.com');
    }

    public static List<Account> newAccountList(Integer count) {
        List<Account> accList = new List<Account>();
        for (Integer i = 0; i < count; i++) {
            String name = 'test' + i;
            String website = 'https://' + name + '.sunbridge.com';
            accList.add(newAccount(name, website));
        }
        return accList;
    }

    public static Account createAccount() {
        Account acc = newAccount();
        insert acc;
        return acc;
    }

    public static List<Account> createAccountList(Integer count) {
        List<Account> accList = newAccountList(count);
        insert accList;
        return accList;
    }

    public static List<Account> getAccountList(Integer count) {
        return [SELECT Id, Name, Website FROM Account LIMIT :count];
    }

    public static Account getAccount() {
        List<Account> accList = getAccountList(1);
        return (!accList.isEmpty()) ? accList.get(0) : null;
    }

    public static Contact newContact(Id accId) {
        return new Contact(
            AccountId = accId,
            LastName = '三部',
            FirstName = '律次',
            Email = 'sunb@example.com',
            Phone = '03-0000-0000',
            MobilePhone = '090-0000-0000',
            MailingPostalCode = '150-0022',
            MailingState = '東京都',
            MailingCity = '渋谷区',
            MailingStreet = '恵比寿南1-5-5\nJR恵比寿ビルB11F'
        );
    }

    public static Contact createContact(Id accId) {
        Contact con = newContact(accId);
        insert con;
        return con;
    }

    public static Contact getContact() {
        return [SELECT Id, LastName, FirstName, Account.Name, Department, Title, Email, Phone, MobilePhone,
            MailingPostalCode, MailingState, MailingCity, MailingStreet, Account.Website FROM Contact LIMIT 1];
    }

    public static ContentVersion newContentVersion() {
        return new ContentVersion(
            Title = 'test',
            VersionData = Blob.valueOf('test'),
            PathOnClient = 'test.png'
        );
    }

    public static ContentVersion createContentVersion() {
        ContentVersion cv = newContentVersion();
        insert cv;
        return cv;
    }

    public static ContentVersion getContentVersion() {
        return [SELECT Id, ContentDocumentId, Title, PathOnClient FROM ContentVersion LIMIT 1];
    }

    public static ContentDistribution newContentDistribution(ContentVersion cv) {
        return new ContentDistribution(
            ContentVersionId = cv.Id,
            Name = cv.Title
        );
    }

    public static ContentDistribution createContentDistribution(ContentVersion cv) {
        ContentDistribution cd = newContentDistribution(cv);
        insert cd;
        return cd;
    }

    public static ContentDistribution getContentDistribution() {
        return [SELECT Id, ContentDocumentId, ContentVersionId, Name FROM ContentDistribution LIMIT 1];
    }

    public static OnlineProfileConfig__c newConfig() {
        return new OnlineProfileConfig__c(
            BaseUrl__c = 'https://onlineprofile.example.com',
            DefaultViewCountLimit__c = 10,
            DefaultViewExpirationDays__c = 1
        );
    }

    public static OnlineProfileConfig__c createConfig() {
        OnlineProfileConfig__c config = newConfig();
        insert config;
        return config;
    }

    public static MyProfile__c newMyProfile(String lastName, String firstName, String email) {
        return new MyProfile__c(
            LastName__c = lastName,
            FirstName__c = firstName,
            Department__c = 'クラウドインテグレーション',
            Title__c = 'マネージャー',
            Email__c = email,
            MobilePhone__c = '090-0000-0000',
            tel__c = '03-0000-0000',
            tel1__c = '03-0000-0001',
            tel2__c = '03-0000-0002',
            CompanyName__c = '株式会社サンブリッジ',
            PostalCode__c = '150-0022',
            State__c = '東京都',
            City__c = '渋谷区',
            Street__c = '恵比寿南1-5-5\nJR恵比寿ビルB11F',
            IsDefault__c = true
        );
    }

    public static MyProfile__c newMyProfile() {
        return newMyProfile('三部', '律次', 'sunb@example.com');
    }

    public static List<MyProfile__c> newMyProfileList(Integer count) {
        List<MyProfile__c> profList = new List<MyProfile__c>();
        for (Integer i = 0; i < count; i++) {
            String lastName = 'test' + i;
            profList.add(newMyProfile(lastName, 'test', lastName + '@example.com'));
        }
        return profList;
    }

    public static MyProfile__c createMyProfile() {
        MyProfile__c prof = newMyProfile();
        insert prof;
        return prof;
    }

    public static List<MyProfile__c> createMyProfileList(Integer count) {
        List<MyProfile__c> profList = newMyProfileList(count);
        insert profList;
        return profList;
    }

    public static List<MyProfile__c> getMyProfileList(Integer count) {
        return [SELECT Id, OwnerId, IsDefault__c, LastName__c, FirstName__c, Department__c, Title__c,
            Email__c, MobilePhone__c, CompanyName__c, Website__c, tel__c, tel1__c, tel2__c,
            PostalCode__c, State__c, City__c, Street__c, 
            ImageUrl__c, ContentVersionId__c,Message__c
            FROM MyProfile__c LIMIT :count];
    }

    public static MyProfile__c getMyProfile() {
        List<MyProfile__c> profList = getMyProfileList(1);
        return (!profList.isEmpty()) ? profList.get(0) : null;
    }

    public static OutboundProfile__c newOutboundProfile(String lastName, String firstName, String email) {
        return new OutboundProfile__c(
            CreatedDate__c = Datetime.now(),
            LastName__c = lastName,
            FirstName__c = firstName,
            Department__c = 'クラウドインテグレーション',
            Title__c = 'マネージャー',
            Email__c = email,
            MobilePhone__c = '090-0000-0000',
            tel__c = '03-0000-0000',
            tel1__c = '03-0000-0001',
            tel2__c = '03-0000-0002',
            CompanyName__c = '株式会社サンブリッジ',
            PostalCode__c = '150-0022',
            State__c = '東京都',
            City__c = '渋谷区',
            Street__c = '恵比寿南1-5-5\nJR恵比寿ビルB11F'
        );
    }

    public static OutboundProfile__c newOutboundProfile() {
        return newOutboundProfile('三部', '律次', 'sunb@example.com');
    }

    public static List<OutboundProfile__c> newOutboundProfileList(Integer count) {
        List<OutboundProfile__c> profList = new List<OutboundProfile__c>();
        for (Integer i = 0; i < count; i++) {
            String lastName = 'test' + i;
            profList.add(newOutboundProfile(lastName, 'test', lastName + '@example.com'));
        }
        return profList;
    }

    public static OutboundProfile__c createOutboundProfile() {
        OutboundProfile__c prof = newOutboundProfile();
        insert prof;
        return prof;
    }

    public static List<OutboundProfile__c> createOutboundProfileList(Integer count) {
        List<OutboundProfile__c> profList = newOutboundProfileList(count);
        insert profList;
        return profList;
    }

    public static List<OutboundProfile__c> getOutboundProfileList(Integer count) {
        return [SELECT Id, OwnerId, Parent__c, LastName__c, FirstName__c, Department__c, Title__c,
            Email__c, MobilePhone__c, CompanyName__c, Website__c, tel__c, tel1__c, tel2__c,
            PostalCode__c, State__c, City__c, Street__c,  ImageUrl__c,
            ViewExpirationDate__c, ViewCountLimit__c, ViewCount__c, Message__c
            FROM OutboundProfile__c LIMIT :count];
    }

    public static OutboundProfile__c getOutboundProfile() {
        List<OutboundProfile__c> profList = getOutboundProfileList(1);
        return (!profList.isEmpty()) ? profList.get(0) : null;
    }

    public static InboundProfile__c getInboundProfile() {
        return [SELECT Id, CompanyName__c, LastName__c, FirstName__c, Email__c, MobilePhone__c, tel__c, tel1__c, tel2__c,
            PostalCode__c, State__c, City__c, Street__c, Website__c,
            Department__c, Title__c FROM InboundProfile__c LIMIT 1];
    }
}