sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/InboundProfile__c.object-meta.xml
<CustomObject>
    <label>受信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>受信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>名</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/InboundProfile__c/fields/OutboundProfile__c.field-meta.xml
<CustomField>
    <fullName>OutboundProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>送信プロフィール</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OutboundProfile__c.Parent__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OutboundProfile__c</referenceTo>
    <relationshipLabel>受信プロフィール</relationshipLabel>
    <relationshipName>InboundProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/OutboundProfile__c.object-meta.xml
<CustomObject>
    <label>送信プロフィール</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>送信プロフィール番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>メール</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/objects/OutboundProfile__c/fields/ViewCount__c.field-meta.xml
<CustomField>
    <fullName>ViewCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>表示回数</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/OnlineProfile/main/default/classes/ProfileExchangerServiceTest.cls
/**
 * Online Profile
 * プロフィール交換Service
 * Test
 */
@IsTest
private with sharing class ProfileExchangerServiceTest {
    @IsTest
    private static void updateViewCount() {
        TestDataFactory.createOutboundProfileList(200);
        List<OutboundProfile__c> outProfList = TestDataFactory.getOutboundProfileList(200);

        Test.startTest();
        ProfileExchangerService.updateViewCount(outProfList);
        Test.stopTest();

        for (OutboundProfile__c outProf : TestDataFactory.getOutboundProfileList(200)) {
            System.assertEquals(1, outProf.ViewCount__c);
        }
    }

    @IsTest
    private static void createInboundProfile() {
        String email = 'meishi@example.com';
        InboundProfile__c inProf = new InboundProfile__c(
            LastName__c = '名刺',
            FirstName__c = '太郎',
            Email__c = email
        );

        Test.startTest();
        ProfileExchangerService.createInboundProfile(new List<InboundProfile__c> { inProf });
        Test.stopTest();

        System.assertEquals(email, TestDataFactory.getInboundProfile().Email__c);
    }
}